localStorage.setItem(
  "products",
  JSON.stringify([
    {
      id: 1,
      productName: "Samsung Phone",
      category: "Phones",
      price: 3000.0,
      Image: "../Images/Products/Phones/1.jpg",
    },
    {
      id: 2,
      productName: "Samsung Note 20",
      category: "Phones",
      price: 3500.0,
      Image: "../Images/Products/Phones/2.jpg",
    },
    {
      id: 3,
      productName: "Realme Black phone",
      category: "Phones",
      price: 2000.0,
      Image: "../Images/Products/Phones/3.jpg",
    },
    {
      id: 4,
      productName: "Realme Gold phone",
      category: "Phones",
      price: 2500.0,
      Image: "../Images/Products/Phones/4.jpg",
    },
    {
      id: 5,
      productName: "IPhone Black",
      category: "Phones",
      price: 2500.0,
      Image: "../Images/Products/Phones/5.jpg",
    },
    {
      id: 6,
      productName: "MacBook Air white",
      category: "Laptops",
      price: 5000.0,
      Image: "../Images/Products/Laptops/1.jpg",
    },
    {
      id: 7,
      productName: "HP Silver Laptop",
      category: "Laptops",
      price: 4599.0,
      Image: "../Images/Products/Laptops/2.jpg",
    },
    {
      id: 8,
      productName: "MacBook Silver",
      category: "Laptops",
      price: 5500.0,
      Image: "../Images/Products/Laptops/3.jpg",
    },
    {
      id: 9,
      productName: "Mouse Brown",
      category: "Mouses",
      price: 40.0,
      Image: "../Images/Products/Mouses/1.jpg",
    },
    {
      id: 10,
      productName: "Apple Mouse White",
      category: "Mouses",
      price: 50.0,
      Image: "../Images/Products/Mouses/2.jpg",
    },
    {
      id: 11,
      productName: "Gaming Mouse Black",
      category: "Mouses",
      price: 55.0,
      Image: "../Images/Products/Mouses/3.jpg",
    },
    {
      id: 12,
      productName: "Keyboard Gaming Black",
      category: "Keyboards",
      price: 150.0,
      Image: "../Images/Products/Keyboards/2.jpg",
    },

    {
      id: 13,
      productName: "Keyboard Slim white",
      category: "Keyboards",
      price: 120.0,
      Image: "../Images/Products/Keyboards/1.jpg",
    },
    {
      id: 14,
      productName: "Headphone Black",
      category: "Headphones",
      price: 120.0,
      Image: "../Images/Products/Headphones/1.jpg",
    },

    {
      id: 15,
      productName: "Premiun Headphone Black",
      category: "Headphones",
      price: 200.0,
      Image: "../Images/Products/Headphones/2.jpg",
    },
    {
      id: 16,
      productName: "Beats Headphone Gold",
      category: "Headphones",
      price: 180.0,
      Image: "../Images/Products/Headphones/3.jpg",
    },
  ])
);
