localStorage.setItem(
  "products",
  JSON.stringify([
    {
      id: 1,
      productName: "Samsung Phone",
      category: "Phones",
      color: "gold",
      price: 3000.0,
      Image: "./Images/Products/Phones/1.jpg",
    },
    {
      id: 2,
      productName: "Samsung Note 20",
      category: "Phones",
      color: "silver",
      price: 3500.0,
      Image: "./Images/Products/Phones/2.jpg",
    },
    {
      id: 3,
      productName: "Realme phone",
      category: "Phones",
      color: "black",
      price: 2000.0,
      Image: "./Images/Products/Phones/3.jpg",
    },
    {
      id: 4,
      productName: "Realme phone",
      category: "Phones",
      color: "gold",
      price: 2500.0,
      Image: "./Images/Products/Phones/4.jpg",
    },
    {
      id: 5,
      productName: "IPhone 15",
      color: "black",
      category: "Phones",
      price: 2500.0,
      Image: "./Images/Products/Phones/5.jpg",
    },
    {
      id: 6,
      productName: "MacBook Air",
      category: "Laptops",
      color: "white",
      price: 5000.0,
      Image: "./Images/Products/Laptops/1.jpg",
    },
    {
      id: 7,
      productName: "HP Laptop",
      category: "Laptops",
      color: "silver",
      price: 4599.0,
      Image: "./Images/Products/Laptops/2.jpg",
    },
    {
      id: 8,
      productName: "MacBook slim",
      category: "Laptops",
      color: "silver",
      price: 5500.0,
      Image: "./Images/Products/Laptops/3.jpg",
    },
    {
      id: 9,
      productName: "Mouse",
      category: "Mouses",
      color: "brown",
      price: 40.0,
      Image: "./Images/Products/Mouses/1.jpg",
    },
    {
      id: 10,
      productName: "Mouse",
      category: "Mouses",
      color: "white",
      price: 50.0,
      Image: "./Images/Products/Mouses/2.jpg",
    },
    {
      id: 11,
      productName: "Gaming Mouse",
      category: "Mouses",
      color: "black",
      price: 55.0,
      Image: "./Images/Products/Mouses/3.jpg",
    },
    {
      id: 12,
      productName: "Keyboard Gaming",
      category: "Keyboards",
      color: "black",
      price: 150.0,
      Image: "./Images/Products/Keyboards/2.jpg",
    },

    {
      id: 13,
      productName: "Keyboard Slim ",
      category: "Keyboards",
      color: "white",
      price: 120.0,
      Image: "./Images/Products/Keyboards/1.jpg",
    },
    {
      id: 14,
      productName: "Headphone",
      category: "Headphones",
      color: "black",
      price: 120.0,
      Image: "./Images/Products/Headphones/1.jpg",
    },

    {
      id: 15,
      productName: "Premiun Headphone",
      category: "Headphones",
      color: "black",
      price: 200.0,
      Image: "./Images/Products/Headphones/2.jpg",
    },
    {
      id: 16,
      productName: "Beats Headphone",
      category: "Headphones",
      color: "gold",
      price: 180.0,
      Image: "./Images/Products/Headphones/3.jpg",
    },
  ])
);
